version: '3.1'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: .docker/web.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/:cached
    tty: true
    stdin_open: true
